import raw from "./decks.json" with { type: "json" };

/**
 * The deck registry. `decks.json` is generated by `scripts/sync-decks.ts` from
 * the standalone deck repositories under `decks/`; commit the snapshot so
 * builds and tests work without the repos checked out.
 */

export interface CardCredit {
  observer: string;
  license: string;
  observationUrl: string;
  observationId: number;
  placeLabel: string;
}

export interface DeckCard {
  name: string;
  front: string;
  back: string;
  invasive: boolean;
  sciName?: string;
  native?: "native" | "non-native" | "unknown";
  rarity?: string | null;
  credits?: CardCredit[];
}

export interface DeckCategory {
  id: string;
  label: string;
  cards: DeckCard[];
}

export interface DeckDef {
  id: string;
  label: string;
  description: string;
  categories: DeckCategory[];
}

export const DECK_DEFS: DeckDef[] = (raw as { decks: DeckDef[] }).decks;

export const DEFAULT_DECK_ID: string = DECK_DEFS[0]?.id ?? "canyonlands";

export function getDeckDef(id: string): DeckDef | undefined {
  return DECK_DEFS.find((d) => d.id === id);
}

/** All category ids used across decks — for scrubbing stale mode URL params. */
export const ALL_CATEGORY_IDS: string[] = [
  ...new Set(DECK_DEFS.flatMap((d) => d.categories.map((c) => c.id))),
];

/**
 * Default invasive lookup for the Card component when a deck isn't specified:
 * a card name flagged invasive in any deck is treated as invasive.
 */
const defaultInvasiveNames: Set<string> = new Set(
  DECK_DEFS.flatMap((d) => d.categories.flatMap((c) => c.cards.filter((x) => x.invasive).map((x) => x.name))),
);

export function defaultInvasive(cardName: string): boolean {
  return defaultInvasiveNames.has(cardName);
}